version: 2.1

orbs:
  node: circleci/node@4.5.0
  puppeteer: threetreeslight/puppeteer@0.1.2

jobs:

  checkout:
    executor:
      name: node/default
    steps:
      - checkout
      - run: rm -rf .git # get rid of that big excess folder
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - node/install-packages
      - run: npm run lint

  build:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - node/install-packages
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./build # Only persist the build files, since persisting large folders (like node_modules) results in long persisting/attaching times

  build-with-ssr:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - node/install-packages
      - run: |
          sudo apt-get update
          sudo apt-get install -y libgbm1
      - puppeteer/install
      - run: npm run ssr
      - persist_to_workspace:
          root: .
          paths:
            - ./build

  deploy:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - node/install-packages
      - run: npm run deploy
      - run: npm run invalidate

workflows:
  all-jobs:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - build:
          filters:
            branches:
              ignore: master
          requires:
            - lint
      - build-with-ssr:
          filters:
            branches:
              only: master
          requires:
            - lint
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build-with-ssr
